name: Publish on GitHub, CurseForge & Modrinth
 
on: [ workflow_dispatch ]

env:
  MINECRAFT_VERSION: 1.21.3
  JAVA_VERSION: 21
  VERSION: 0.2.1+1.21.3
  RELEASE_NAME:  Chiseled enchanting table Beta 0.2.1 for Minecraft 1.21.3
  MODRINTH_ID: ${{ secrets.PUBLISH_MODRINTH_ID }}
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  # CURSEFORGE_ID: ${{ secrets.PUBLISH_CURSEFORGE_ID }}
  # CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}           

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Environment Variables
        run: env

      - name: Checkout Repository
        uses: actions/checkout@v4.2.2
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v3.14.1
        with:
          distribution: "temurin"
          java-version: ${{env.JAVA_VERSION}}

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew clean build
        
      - name: Publish (CurseForge/Modrinth/GitHub)
        uses: Kira-NT/mc-publish@v3.3.0
        with:
          # curseforge-id: "${{env.CURSEFORGE_ID}}"
          # curseforge-token: "${{env.CURSEFORGE_TOKEN}}"
          
          modrinth-id: "${{env.MODRINTH_ID}}"
          modrinth-token: "${{env.MODRINTH_TOKEN}}"
          
          github-tag: "v${{env.VERSION}}"
          github-token: "${{env.GITHUB_TOKEN}}"

          name: "${{env.RELEASE_NAME}}"
          version: "${{env.VERSION}}"
          version-type: release
          changelog-file: CHANGELOG.md

          loaders: fabric
          game-versions: "${{env.MINECRAFT_VERSION}}"
          java: "${{env.JAVA_VERSION}}"
